
export const COUNTIES = [
  { number: '01', code: 'MSA', name: 'Mombasa' },
  { number: '02', code: 'KWL', name: 'Kwale' },
  { number: '03', code: 'KLF', name: 'Kilifi' },
  { number: '04', code: 'TRV', name: 'Tana River' },
  { number: '05', code: 'LMU', name: 'Lamu' },
  { number: '06', code: 'TVT', name: 'Taita/Taveta' },
  { number: '07', code: 'GRS', name: 'Garissa' },
  { number: '08', code: 'WJR', name: 'Wajir' },
  { number: '09', code: 'MDR', name: 'Mandera' },
  { number: '10', code: 'MST', name: 'Marsabit' },
  { number: '11', code: 'ISO', name: 'Isiolo' },
  { number: '12', code: 'MRU', name: 'Meru' },
  { number: '13', code: 'TKN', name: 'Tharaka-Nithi' },
  { number: '14', code: 'EMB', name: 'Embu' },
  { number: '15', code: 'KTI', name: 'Kitui' },
  { number: '16', code: 'MCK', name: 'Machakos' },
  { number: '17', code: 'MKN', name: 'Makueni' },
  { number: '18', code: 'NRA', name: 'Nyandarua' },
  { number: '19', code: 'NYR', name: 'Nyeri' },
  { number: '20', code: 'KRG', name: 'Kirinyaga' },
  { number: '21', code: 'MRA', name: 'Murang&apos;a' },
  { number: '22', code: 'KBU', name: 'Kiambu' },
  { number: '23', code: 'TKN', name: 'Turkana' },
  { number: '24', code: 'WPT', name: 'West Pokot' },
  { number: '25', code: 'SMR', name: 'Samburu' },
  { number: '26', code: 'TNR', name: 'Trans Nzoia' },
  { number: '27', code: 'UGU', name: 'Uasin Gishu' },
  { number: '28', code: 'ELM', name: 'Elgeyo/Marakwet' },
  { number: '29', code: 'NDI', name: 'Nandi' },
  { number: '30', code: 'BRO', name: 'Baringo' },
  { number: '31', code: 'LKP', name: 'Laikipia' },
  { number: '32', code: 'NRU', name: 'Nakuru' },
  { number: '33', code: 'NRK', name: 'Narok' },
  { number: '34', code: 'KJO', name: 'Kajiado' },
  { number: '35', code: 'KRC', name: 'Kericho' },
  { number: '36', code: 'BOM', name: 'Bomet' },
  { number: '37', code: 'KKG', name: 'Kakamega' },
  { number: '38', code: 'VHG', name: 'Vihiga' },
  { number: '39', code: 'BGA', name: 'Bungoma' },
  { number: '40', code: 'BSA', name: 'Busia' },
  { number: '41', code: 'SYA', name: 'Siaya' },
  { number: '42', code: 'KSM', name: 'Kisumu' },
  { number: '43', code: 'HBY', name: 'Homa Bay' },
  { number: '44', code: 'MGR', name: 'Migori' },
  { number: '45', code: 'KSI', name: 'Kisii' },
  { number: '46', code: 'NYM', name: 'Nyamira' },
  { number: '47', code: 'NBI', name: 'Nairobi City' },
];

export const SERVICE_CATEGORIES = [
  'Baking services',
  'Barber',
  'Beverage services & bar',
  'Cargo loading/Off-loading',
  'Carpentry',
  'Catering',
  'Chauffeur/Driving',
  'Coffee/tea & beverage services',
  'Courier',
  'Data analysis',
  'Digital creation/advertising',
  'Driving services',
  'Electronics repair',
  'Equipment assembly',
  'Event set-up/Take-down',
  'Fumigation',
  'Function/Events services',
  'Funeral & Final rites services',
  'General labor/lifting',
  'Grocery shopping/Pharmaceutical pick-up',
  'Gutter cleaning',
  'Hand/Machine Laundry',
  'Home cleaning',
  'Home cooking',
  'Home nursing',
  'Home repairs & fitting',
  'Home/Office administration',
  'Home/Office decoration',
  'IT/Networking',
  'Junk removal',
  'Lawn & Gardening',
  'Masonry',
  'Mechanic',
  'Mobile car wash',
  'Moving/Relocation',
  'Music & Performance art',
  'Note taking/writing/Editing',
  'Personal wellness & therapy',
  'Personal/Home security',
  'Plumbing',
  'Pool maintenance',
  'Salon & Beauty',
  'Shoe shine & repair',
];

export const TRAINING_OPTIONS = [
  'Baking services',
  'Barber',
  'Beverage services & bar',
  'Cargo loading/Off-loading',
  'Carpentry',
  'Catering',
  'Chauffeur/Driving',
  'Coffee/tea & beverage services',
  'Courier',
  'Data analysis',
  'Digital creation/advertising',
  'Driving services',
  'Electronics repair',
  'Equipment assembly',
  'Event set-up/Take-down',
  'Fumigation',
  'Function/Events services',
  'Funeral & Final rites services',
  'General labor/lifting',
  'Grocery shopping/Pharmaceutical pick-up',
  'Gutter cleaning',
  'Hand/Machine Laundry',
  'Home cleaning',
  'Home cooking',
  'Home nursing',
  'Home repairs & fitting',
  'Home/Office administration',
  'Home/Office decoration',
  'IT/Networking',
  'Junk removal',
  'Lawn & Gardening',
  'Masonry',
  'Mechanic',
  'Mobile car wash',
  'Moving/Relocation',
  'Music & Performance art',
  'Note taking/writing/Editing',
  'Personal wellness & therapy',
  'Personal/Home security',
  'Plumbing',
  'Pool maintenance',
  'Salon & Beauty',
  'Shoe shine & repair',
];
